#!/bin/sh

cd /home/app/.ssh
#ssh -i id_rsa app@APP.SERVER.IP.ADDRESS <<EOF
ssh -i id_rsa app@54.164.213.0 << EOF
  cd ~/node-demo
  git pull
  npm install --production
  forever restartall
  exit
EOF
